### ISSUE TITLE
Options for different projections

### ISSUE THREAD

**Issue by luizhdasilva** [PORTAL-CEOS/ANHALYZE#13]
The projection used in the figures are limited to one option and the parameters used works for one single region (Hudson Bay).

**Comment by jeenriquez** [comment]
Once you finish this and before merging, may be worth looking at [tests/map_projections.py](https://github.com/PORTAL-CEOS/ANHALYZE/blob/main/anhalyze/tests/map_projections.py) and update if necessary.

**Comment by jeenriquez** [comment]
@luizhdasilva could you please update [map_projections.py](https://github.com/PORTAL-CEOS/ANHALYZE/blob/main/anhalyze/tests/map_projections.py)? So that we can close this issue. Thanks!

**Comment by luizhdasilva** [comment]
> @luizhdasilva could you please update [map_projections.py](https://github.com/PORTAL-CEOS/ANHALYZE/blob/main/anhalyze/tests/map_projections.py)? So that we can close this issue. Thanks!

I was wondering, should the test output be one figure per projection or the user should be able to pick a projection to run an individual test for a particular projection?

**Comment by jeenriquez** [comment]
We are good for now. We'll see later what kind of unit test we'll do.
