### ISSUE TITLE
Updating standard color maps for given data variable.

### ISSUE THREAD

**Issue by jeenriquez** [PORTAL-CEOS/ANHALYZE#14]
Want to use standard color maps for given data variable in [get_plot_config](https://github.com/PORTAL-CEOS/ANHALYZE/blob/df45a306fe5c6fbdc90091cdc3658cceeab5c60b/anhalyze/core/anhalyze_plot_utils.py#L24)

Something along [these lines](https://ferret.pmel.noaa.gov/Ferret/faq/ferret-color-palettes).

**Comment by jeenriquez** [comment]
Also useful for this conversation [python cmaps](https://matplotlib.org/stable/users/explain/colors/colormaps.html).

**Comment by luizhdasilva** [comment]
[Cmocean](https://matplotlib.org/cmocean/) can be use as the default colormap source.

**Comment by jeenriquez** [comment]
@luizhdasilva latest version of the code is merged. You should be able to rebase/merge what you have done on this now.
