### ISSUE TITLE
Not importing the package on a venv inside PORTAL

### ISSUE THREAD

**Issue by luizhdasilva** [PORTAL-CEOS/ANHALYZE#27]
I cannot import the package while using it in a virtual environment inside the PORTAL machine.
When doing this on a Jupyter Notebook installed within my virtual environment: 

```python
import anhalyze as ah
``` 
The notebook is returning:

![Screenshot from 2024-11-05 12-36-33(1)](https://github.com/user-attachments/assets/cab19227-f3a3-4312-9ead-f029bd57d084)

**Comment by jeenriquez** [comment]
couple of questions:
- did you check if the file (toml) really exists. 
- how did you install anhalyize in your env? 
- could you try importing anhalyze in ipython?

**Comment by jeenriquez** [comment]
@luizhdasilva  I was able to reproduce the error. I was able to fix it by installing again anhalyze per the instruction in the README.
