### ISSUE TITLE
Error plotting 2D variables

### ISSUE THREAD

**Issue by luizhdasilva** [PORTAL-CEOS/ANHALYZE#8]
The method show_var_data_map is returning an error related with data dimension: input z must be 2D, not 1D.

**Comment by luizhdasilva** [comment]
Snippet to reproduce the issue:

`data = ah.AnhaDataset('ANHA4-WLS001_y1980m01d05_gridT.nc')
data.apply_mask('ANHA4_mask.nc')
bbdata = aa.sel([60,84],[-90,-60])
bbdata.show_var_data_map(var='sohmld')`

**Comment by jeenriquez** [comment]
Bug fixed. Thanks @luizhdasilva!
